### ISSUE TITLE
A case for a 5 star rating system

### ISSUE THREAD

**Issue by smmalmansoori** [Calinou/godot-asset-library-laravel#201]
I noticed from the database migration files that you're using an upvote/downvote mechanic in the reviews which is then calculated as a score in the asset. However, this doesn't make for a good user experience for either the user or the asset author.

### Not informative if used as a score
* Asset X - score 30

This treats **60 upvotes and 30 downvotes** in equal value to **30 upvotes and 0 downvotes** which doesn't help the user in making a decision.

### Visually confusing if used as upvote/downvote
* Item 1 - 89x:+1:, 33x:-1:
* Item 2 - 113x:+1:, 73x:-1:
* Item 3 - 66x:+1:, 73x:-1:
* Item 4 - 7x:+1:, 1x:-1:

Vs.

* Item 1 - 4.9:star:
* Item 2 - 4.5:star:
* Item 3 - 3.0:star:
* Item 4 - Not enough reviews

The second one is easier to determine when given 4 options, much less 400 options.

[The above example is borrowed from an answer in stackexchange](https://ux.stackexchange.com/a/87236)

### It's discouraging for the author and limiting for the end-user
The end-users here are developers just like the asset author, they can give informative feedback and a more accurate score

**Comment by Calinou** [comment]
Sorry, but I believe star ratings are the worst approach to rating stuff online:

[![xkcd Star Ratings](https://imgs.xkcd.com/comics/star_ratings.png)](https://xkcd.com/1098/)

Using Wilson score for sorting with the current upvote/downvote approach will lead to better sorting.
