### ISSUE TITLE
Implement server-side download hash computing

### ISSUE THREAD

**Issue by Calinou** [Calinou/godot-asset-library-laravel#44]
The server should compute the SHA-256 checksum of all version downloads (both if the link is inferred from the version tag or custom). It should then be persisted to the database.

This hash could also be displayed with small text on asset detail pages.

**Comment by Calinou** [comment]
Note that a workaround was implemented with https://github.com/Calinou/godot-asset-library-laravel/commit/8ac10f9b2a7990792caf418869988a495be54429f, so the API should still be functional for now.

**Comment by bojidar-bg** [comment]
As hashes were removed in the official asset library (currently replaced by using exact commit hashes when specifying a download link), I suppose this can be closed?

**Comment by Calinou** [comment]
@bojidar-bg Indeed, thanks for the reminder :slightly_smiling_face:
