### ISSUE TITLE
Add a Docker image for easier development setup

### ISSUE THREAD

**Issue by Calinou** [Calinou/godot-asset-library-laravel#58]
Having a Docker image that can be spun up using `docker-compose` would make it easier to onboard new contributors. I didn't make one since I have no need for it myself, but help is welcome in adding a Docker setup.

The image should use PHP 7.2 for compatibility with the production setup.

**Comment by QuentinCaffeino** [comment]
Hello, I'm willing to contribute if this is still open.
Could you provide more info about env? Like database type/version, and whatever else is required to run this website.

**Comment by QuentinCaffeino** [comment]
I see it requires Mysql/Maria but I couldn't find anywhere at least minimal version.
Also, does this website require any kind of special binaries being present in the system?

**Comment by Calinou** [comment]
@QuentinCaffeino Thanks for looking into it :slightly_smiling_face: 

> Could you provide more info about env? Like database type/version, and whatever else is required to run this website.

The production environment uses PHP 7.2.x (with mbstring and pdo_mysql) and MySQL 5.7.x.

> Also, does this website require any kind of special binaries being present in the system?

Not as far as I know.
